### ISSUE TITLE
testing strategy

### ISSUE THREAD

**Issue by waddella** [openpharma/staged.dependencies#33]
@maximilianmordig please join the discussion

**Comment by maximilianmordig** [comment]
Where is the discussion taking place?
This seems to be related to #37.

**Comment by waddella** [comment]
we also need unit tests. Please propose a design pattern to test the framework without accessing the internet.

**Comment by nikolas-burkoff** [comment]
Some thoughts here:
- Easier to test after #72
- Adding more unit tests into code base - some functions in utils.R and branching_strategy.R are ready for testing - in other cases we can refactor out logic like done [here](https://github.com/openpharma/staged.dependencies/blob/584eff8ba9e0e54ab2d6a42fc1c2cbfcee3dd49f/R/dependencies.R#L870)
- Add code into the github action to run some integration tests for example checking out the stageddeps.X packages and running install_deps, build, check etc. on them
- The code using git doesn't know about the rest of the package (and can be tested separately - we could have a dummy repo or we could rely on above to check it's working) so we can mock out the git stuff to test the graph building - may want some small refactors to make that easier
- Having the option to choose a caching directory could then enable us to test parts of the code which use it - we can put dummy DESC and yaml files in it (ideally we want to install packages using remotes rather than from the cache... anyway)

**Comment by nikolas-burkoff** [comment]
Done - see comment above
