### ISSUE TITLE
investigate if you can build the dependency graph without the cloning the repos

### ISSUE THREAD

**Issue by waddella** [openpharma/staged.dependencies#35]
You would use:

  - `gh` and the rest api (graphql) to get
       -  the available branches & tags
       -  `DESCRIPTION` file
       -  `staged_dependecies.yaml`  file

should work on github (internal, external) & gitlab.

**Comment by nikolas-burkoff** [comment]
If you can build the dependency graph without cloning then this should be the default option in all cases in my opinion

**Comment by maximilianmordig** [comment]
`gh` only works with GitHub, not with Gitlab and other git hubs. Not all git hubs may have a REST API to download single files.
We could do a shallow clone or partial clone (https://docs.gitlab.com/ee/topics/git/partial_clone.html), although the latter is still very experimentall and its behavior is subject to change.

**Comment by waddella** [comment]
let's constrain `staged.dependencies` to only work with GitHub and GitLab APIs to make this feature possible. Note, this will have impact on `local_repos`.

Also, with this feature we only need to download `DESCRIPTION` and `staged_depencies.yaml` files from the correct branch determined with `gh`. Use `remotes::install_*` which takes over some complexity.

**Comment by waddella** [comment]
We will get back to this once we have features of `staged.dependecies` established. This would be a major refactor.

**Comment by nikolas-burkoff** [comment]
We also need to make sure gitlab automation does not break https://github.com/openpharma/staged.dependencies/issues/98

**Comment by nikolas-burkoff** [comment]
**Can you get the information without cloning?**

1) Gitlab

- Branches - graphQL
```
{
  project(fullPath:"x/y/z"){
    repository{
      branches: branchNames(searchPattern:"*", offset:0, limit:100)
    }
  }
}
```

- Tags - as far as I can tell only REST https://docs.gitlab.com/ee/api/tags.html (which requires knowing the project ID first)

- Files:
```
{
  project(fullPath:"x/y/z"){
    repository{
      blobs(paths: ["DESCRIPTION", "staged_dependencies.yaml"], ref:"main"){
        nodes{
          rawBlob
        }   
      }
    }
  }
}
```

2) Github

- Branches and tags:

```
{
  repository(owner: "openpharma", name: "stageddeps.garden") {
    branches: refs(first: 100, refPrefix: "refs/heads/") {
      nodes {
        name
      }
    }
    tags: refs(first: 100, refPrefix: "refs/tags/") {
      nodes {
        name
      }
    }
  }
}
```

- Files (with `variables: {"repo_name" :"stageddeps.garden"}`)
```
query GetFiles($repo_owner: String = "openpharma", $repo_name: String!, 
$desc_expression: String = "main:DESCRIPTION", $yaml_expression: String = "main:staged_dependencies.yaml") {
  repository(owner: $repo_owner, name: $repo_name) {
    staged_deps: object(expression: $yaml_expression) {
      ... on Blob {
        text
      }
    }
    description: object(expression: $desc_expression) {
      ... on Blob {
        text
      }
    }
  }
}
```

In order to use these we would need to refactor code so that dependent on which host type it is the way we get this information is possible. This could also remove the somewhat hacky error handling found [here](https://github.com/openpharma/staged.dependencies/blob/d113616347a31aab3f4da66aa7e48ffd093d0ab7/R/git_tools.R#L72)  

Also need to handle auth and pagination in case of large numbers of branches/tags

**Further Impacts on staged.deps:** 

- In theory could rely on remotes to install packages but note issue 321 in remotes (it's been 2 years so unlikely to be fixed) - there could be ways around it but would we need to clone package repos before installing them anyway? Also if we are running `build_check_install` or `check_downstream` we would still need the repo cloned? 
- Would need to remove option for "local" packages unless cache is only for local repos/we point directly to wherever the local repo is stored BUT would want "current" package to still take the current code not a remote version especially for gitlab automation
- There are a few unexpected places in the code where having the DESCRIPTION file cached is quite helpful i.e. [here](https://github.com/openpharma/staged.dependencies/blob/d113616347a31aab3f4da66aa7e48ffd093d0ab7/R/git_tools.R#L139) 
- Tests, docs etc. need updating

**Comment by nikolas-burkoff** [comment]
Closing this - see #105 as follow on work
