### ISSUE TITLE
Please Address Warnings

### ISSUE THREAD

**Issue by waddella** [openpharma/staged.dependencies#60]
With `install_deps` (in osprey) I get:

```
Warning messages:
1: In git2r::remote_ls(remote$url, credentials = remote$credentials) :
  Error in 'git2r_remote_ls'

2: In git2r::remote_ls(remote$url, credentials = remote$credentials) :
  Error in 'git2r_remote_ls'

3: In git2r::remote_ls(remote$url, credentials = remote$credentials) :
  Error in 'git2r_remote_ls'

4: In git2r::remote_ls(remote$url, credentials = remote$credentials) :
  Error in 'git2r_remote_ls'

5: In git2r::remote_ls(remote$url, credentials = remote$credentials) :
  Error in 'git2r_remote_ls'

6: In git2r::remote_ls(remote$url, credentials = remote$credentials) :
  Error in 'git2r_remote_ls'

7: In git2r::remote_ls(remote$url, credentials = remote$credentials) :
  Error in 'git2r_remote_ls'

8: In git2r::remote_ls(remote$url, credentials = remote$credentials) :
  Error in 'git2r_remote_ls'

9: In git2r::remote_ls(remote$url, credentials = remote$credentials) :
  Error in 'git2r_remote_ls'

```

**Comment by nikolas-burkoff** [comment]
So this comes from:
![image](https://user-images.githubusercontent.com/15201933/128839804-1f28e542-461a-4d7e-9446-d42b29af5d94.png)

**Comment by nikolas-burkoff** [comment]
This is also be problematic for bioconductor packages so #54 will fail e.g. for teal
![image](https://user-images.githubusercontent.com/15201933/128999510-ff9d094f-9e5a-4a13-9d52-8b28b8ebe8c7.png)

**Comment by maximilianmordig** [comment]
We should not ignore warnings, as we may ignore important warnings.
The function `remotes::install_deps` is only designed for CRAN dependencies. R assumes that all packages are publicly accessible. The remotes package allows to pass an auth token, but only one such auth token (which does not work if the upstream dependencies require different tokens).
We could rewrite `remotes:::dev_package_deps` so that it ignores the internal upstream dependencies. We need to take into account the bioconductor logic as well. Then, we can call `remotes::update`.

As a hack, we can also remove the internal dependencies manually from the DESCRIPTION file, call this function and undo the changes afterwards. (This is maybe the easiest solution.)

We can also file an issue to `remotes` saying that one should be able to set auth tokens at a github host level, repository level and ask with the `credentials` package if this fails.
